# Generated by Django 4.1.4 on 2023-01-28 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Graph_edges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edges_from', models.CharField(max_length=200)),
                ('edges_to', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Graph_nodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nodes_id', models.CharField(max_length=100)),
                ('nodes_text', models.CharField(max_length=30)),
            ],
        ),
    ]
